import examples.«five-primes».RosserLcmCertificate

namespace TaoFivePrimes

set_option maxRecDepth 16384
set_option maxHeartbeats 4000000
set_option exponentiation.threshold 200000

/-- Generated integer certificates, all checked by the Lean kernel. -/
theorem rosser_up_to_1000 (n : ℕ) (hn : 0 < n) (hN : n ≤ 1000) :
    Chebyshev.psi (n : ℝ) < 1.03883 * (n : ℝ) := by
  have hcover : (1 ≤ n ∧ n ≤ 1) ∨ (2 ≤ n ∧ n ≤ 2) ∨ (3 ≤ n ∧ n ≤ 4) ∨ (5 ≤ n ∧ n ≤ 6) ∨ (7 ≤ n ∧ n ≤ 8) ∨ (9 ≤ n ∧ n ≤ 10) ∨ (11 ≤ n ∧ n ≤ 12) ∨ (13 ≤ n ∧ n ≤ 15) ∨ (16 ≤ n ∧ n ≤ 16) ∨ (17 ≤ n ∧ n ≤ 18) ∨ (19 ≤ n ∧ n ≤ 22) ∨ (23 ≤ n ∧ n ≤ 24) ∨ (25 ≤ n ∧ n ≤ 28) ∨ (29 ≤ n ∧ n ≤ 30) ∨ (31 ≤ n ∧ n ≤ 31) ∨ (32 ≤ n ∧ n ≤ 32) ∨ (33 ≤ n ∧ n ≤ 36) ∨ (37 ≤ n ∧ n ≤ 40) ∨ (41 ≤ n ∧ n ≤ 42) ∨ (43 ≤ n ∧ n ≤ 46) ∨ (47 ≤ n ∧ n ≤ 48) ∨ (49 ≤ n ∧ n ≤ 52) ∨ (53 ≤ n ∧ n ≤ 58) ∨ (59 ≤ n ∧ n ≤ 60) ∨ (61 ≤ n ∧ n ≤ 66) ∨ (67 ≤ n ∧ n ≤ 70) ∨ (71 ≤ n ∧ n ≤ 72) ∨ (73 ≤ n ∧ n ≤ 78) ∨ (79 ≤ n ∧ n ≤ 82) ∨ (83 ≤ n ∧ n ≤ 88) ∨ (89 ≤ n ∧ n ≤ 96) ∨ (97 ≤ n ∧ n ≤ 102) ∨ (103 ≤ n ∧ n ≤ 106) ∨ (107 ≤ n ∧ n ≤ 108) ∨ (109 ≤ n ∧ n ≤ 112) ∨ (113 ≤ n ∧ n ≤ 113) ∨ (114 ≤ n ∧ n ≤ 120) ∨ (121 ≤ n ∧ n ≤ 126) ∨ (127 ≤ n ∧ n ≤ 130) ∨ (131 ≤ n ∧ n ≤ 136) ∨ (137 ≤ n ∧ n ≤ 148) ∨ (149 ≤ n ∧ n ≤ 156) ∨ (157 ≤ n ∧ n ≤ 166) ∨ (167 ≤ n ∧ n ≤ 172) ∨ (173 ≤ n ∧ n ≤ 178) ∨ (179 ≤ n ∧ n ≤ 190) ∨ (191 ≤ n ∧ n ≤ 196) ∨ (197 ≤ n ∧ n ≤ 198) ∨ (199 ≤ n ∧ n ≤ 210) ∨ (211 ≤ n ∧ n ≤ 226) ∨ (227 ≤ n ∧ n ≤ 238) ∨ (239 ≤ n ∧ n ≤ 250) ∨ (251 ≤ n ∧ n ≤ 262) ∨ (263 ≤ n ∧ n ≤ 270) ∨ (271 ≤ n ∧ n ≤ 280) ∨ (281 ≤ n ∧ n ≤ 288) ∨ (289 ≤ n ∧ n ≤ 306) ∨ (307 ≤ n ∧ n ≤ 316) ∨ (317 ≤ n ∧ n ≤ 336) ∨ (337 ≤ n ∧ n ≤ 352) ∨ (353 ≤ n ∧ n ≤ 366) ∨ (367 ≤ n ∧ n ≤ 382) ∨ (383 ≤ n ∧ n ≤ 400) ∨ (401 ≤ n ∧ n ≤ 420) ∨ (421 ≤ n ∧ n ≤ 438) ∨ (439 ≤ n ∧ n ≤ 456) ∨ (457 ≤ n ∧ n ≤ 466) ∨ (467 ≤ n ∧ n ≤ 486) ∨ (487 ≤ n ∧ n ≤ 502) ∨ (503 ≤ n ∧ n ≤ 522) ∨ (523 ≤ n ∧ n ≤ 546) ∨ (547 ≤ n ∧ n ≤ 570) ∨ (571 ≤ n ∧ n ≤ 598) ∨ (599 ≤ n ∧ n ≤ 618) ∨ (619 ≤ n ∧ n ≤ 642) ∨ (643 ≤ n ∧ n ≤ 660) ∨ (661 ≤ n ∧ n ≤ 682) ∨ (683 ≤ n ∧ n ≤ 708) ∨ (709 ≤ n ∧ n ≤ 738) ∨ (739 ≤ n ∧ n ≤ 768) ∨ (769 ≤ n ∧ n ≤ 808) ∨ (809 ≤ n ∧ n ≤ 840) ∨ (841 ≤ n ∧ n ≤ 876) ∨ (877 ≤ n ∧ n ≤ 910) ∨ (911 ≤ n ∧ n ≤ 952) ∨ (953 ≤ n ∧ n ≤ 996) ∨ (997 ≤ n ∧ n ≤ 1000) := by omega
  rcases hcover with h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h
  · exact rosser_interval_of_power 1 1 1 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 2 2 2 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 3 4 4 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 5 6 6 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 7 8 10 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 9 10 12 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 11 12 15 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 13 15 19 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 16 16 20 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 17 18 24 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 19 22 28 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 23 24 33 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 25 28 37 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 29 30 42 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · have heq : n = 31 := by omega
    subst n
    have hp := psi_mul_le_of_lcm_power 31 1000 46038 (by decide)
    norm_num at hp ⊢
    linarith
  · have heq : n = 32 := by omega
    subst n
    have hp := psi_mul_le_of_lcm_power 32 1000 47038 (by decide)
    norm_num at hp ⊢
    linarith
  · exact rosser_interval_of_power 33 36 48 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 37 40 53 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 41 42 58 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 43 46 64 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 47 48 69 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 49 52 72 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 53 58 78 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 59 60 84 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 61 66 90 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 67 70 96 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 71 72 103 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 73 78 109 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 79 82 117 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 83 88 123 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 89 96 130 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 97 102 143 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 103 106 150 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 107 108 156 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 109 112 163 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · have heq : n = 113 := by omega
    subst n
    have hp := psi_mul_le_of_lcm_power 113 1000 169354 (by decide)
    norm_num at hp ⊢
    linarith
  · exact rosser_interval_of_power 114 120 170 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 121 126 176 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 127 130 184 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 131 136 191 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 137 148 205 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 149 156 219 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 157 166 234 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 167 172 245 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 173 178 252 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 179 190 267 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 191 196 283 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 197 198 290 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 199 210 298 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 211 226 313 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 227 238 337 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 239 250 354 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 251 262 371 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 263 270 387 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 271 280 404 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 281 288 420 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 289 306 432 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 307 316 457 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 317 336 474 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 337 352 502 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 353 366 523 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 367 382 549 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 383 400 574 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 401 420 600 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 421 438 627 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 439 456 653 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 457 466 680 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 467 486 697 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 487 502 724 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 503 522 752 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 523 546 775 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 547 570 811 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 571 598 848 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 599 618 894 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 619 642 925 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 643 660 962 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 661 682 990 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 683 708 1018 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 709 738 1058 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 739 768 1106 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 769 808 1144 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 809 840 1212 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 841 876 1256 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 877 910 1305 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 911 952 1364 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 953 996 1428 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)
  · exact rosser_interval_of_power 997 1000 1438 (by decide) (by norm_num)
      n (by exact_mod_cast h.1) (by exact_mod_cast h.2)

end TaoFivePrimes
